fix: allow default model mappings in config yaml
in PR !180, the ability to set the `default-model-mappings` in config
yaml was removed, this PR restores that ability.

unfortunately, this also means reverting a cleaner config merging
solution, however, removing the `#[serde(skip)]` attribute means that
the Gateway fails to startup with the error message:

```
thread 'main' panicked at ai-gateway/src/config/mod.rs:93:68:
called `Result::unwrap()` on an `Err` value: default-model-mapping.anthropic.claude-3-5-sonnet-20240620-v1:0[0]
                                                              ^
invalid postfix
expected `[`, `.`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Since configuring these global mappings is a intentional feature

(see [docs](https://docs.helicone.ai/ai-gateway/config#param-default-model-mapping))

we have to revert this cleanup until we can remove the `#[serde(skip)]`
and have config deserialization work as expected, including for the
default model mappings